Initial sample
Azure-Samples/ms-identity-javascript-nodejs-desktop pull request #1
Opened 2021-01-18 05:22 UTC by derisen

## Purpose

* This PR adds an Electron desktop app that is calling MS Graph API with MSAL Node using auth code with PKCE.
* This sample is meant to be used as a **quickstart** sample.

## Does this introduce a breaking change?

```
[ ] Yes
[ x ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ x ] New sample
```

## How to Test
*  Get the code

```
git clone https://github.com/Azure-Samples/ms-identity-javascript-nodejs-desktop.git
cd ms-identity-javascript-nodejs-desktop
git checkout sample
npm install
```

2021-01-20 00:38 UTC, idg-sam commented on README.md
> +1. [Register a new application](https://docs.microsoft.com/azure/active-directory/develop/scenario-desktop-app-registration) in the [Azure Portal](https://portal.azure.com).
```suggestion
1. Register a [desktop app that calls web APIs](https://docs.microsoft.com/azure/active-directory/develop/scenario-desktop-app-registration) in the [Azure Portal](https://portal.azure.com).
```

2021-01-20 00:40 UTC, idg-sam commented on README.md
> +1. [Register a new application](https://docs.microsoft.com/azure/active-directory/develop/scenario-desktop-app-registration) in the [Azure Portal](https://portal.azure.com).
minor change to link

2021-01-20 00:49 UTC, idg-sam commented on README.md
> +1. Clone this repository `git clone https://github.com/Azure-Samples/ms-identity-javascript-nodejs-desktop.git`
```suggestion
    - Navigate to the Authentication blade in the app registration.
    - Click add a platform and choose **Mobile and Desktop application.**
    - For the **redirect URI**, choose custom redirect URI. Enter `msal://redirect` into the input box.
1. Clone this repository `git clone https://github.com/Azure-Samples/ms-identity-javascript-nodejs-desktop.git`
```

2021-01-20 00:51 UTC, Shama-K reviewed
Sign-in with a user account and sign-out. Click Sign in button, it will sign-in automatically with the same user.

2021-01-20 01:20 UTC, idg-sam commented on README.md
> +    - Click add a platform and choose **Mobile and Desktop application.**
```suggestion
    - Be sure to **remove** any platforms registered here (e.g. web application, SPA, etc)
    - Click add a platform and choose **Mobile and Desktop application.**
```

2021-01-22 22:54 UTC, kalyankrishna1 commented on README.md
> +This sample demonstrates how to use [MSAL Node (Preview)](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node) to sign-in a user and acquire an access token for
>with PKCE [](start = 315, length = 9)

with PKCE flow

2021-01-22 22:55 UTC, kalyankrishna1 commented on README.md
> +* Calling a web API
are these four documented somewhere? or are they links to sections in README?

2021-01-22 22:56 UTC, kalyankrishna1 commented on README.md
> +> :information_source: *note*: This is for multi-tenant applications located on the global Azure cloud. For more information, see: [Use MSAL in a national cloud environment](https://docs.microsoft.co
>global [](start = 84, length = 6)

global->Global

2021-01-22 22:57 UTC, kalyankrishna1 commented on README.md
> +> :information_source: *note*: This is for multi-tenant applications located on the global Azure cloud. For more information, see: [Use MSAL in a national cloud environment](https://docs.microsoft.co
>global Azure cloud [](start = 84, length = 18)

link to [https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud](https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud)

2021-01-22 23:08 UTC, kalyankrishna1 commented on README.md
> +    1. Replace the string `Enter_the_Client_Secret_Here` with the client secret you created on Azure AD portal.
>Replace the string `Enter_the_Client_Secret_Here` with the client secret you created on Azure AD portal. [](start = 7, length = 104)

it does not exists

2021-01-22 23:12 UTC, kalyankrishna1 requested changes
:clock1:

2021-01-22 23:12 UTC, kalyankrishna1 approved these changes
:shipit:

2021-02-03 12:32 UTC, samuelkubai approved these changes
LGTM

2021-02-05 19:53 UTC, hectormmg approved these changes
Looks great!

2021-02-11 22:02 UTC, merged